Update Dockerfile
kmahyyg/ztncui-aio pull request #7
Opened 2021-12-03 16:31 UTC by pjv

Change to nodejs 16 to successfully build ZeroTier v. 1.84

2021-12-03 17:24 UTC, kmahyyg commented
Zerotier is a c/cpp-based program. Ztncui is the one who use nodejs.

However, according to https://github.com/key-networks/ztncui#prerequisites . Ztncui should use nodejs v14.

Different versions(even they are LTS, but not a same major version) might lead to unwanted compiled program and unknown execution results.

Refuse to merge due to consideration of compatibility. Please ask upstream if they support nodejs v16 or not.

2021-12-03 18:52 UTC, pjv commented
Hi @kmahyyg,

All I know is that when I tried to build an updated image of ztncui using the Dockerfile in the HEAD of the master branch here (with `ENV NODEJS_MAJOR=14`), a container spun up from the resulting image would not put up the web app. When I shelled into the container and did this: `./start_ztncui.sh`, the output looked like this:

````
ZTNCUI ENV CONFIGURATION:
NODE_ENV=production
MYADDR=[redacted]
HTTP_PORT=8000
HTTP_ALL_INTERFACES=yes
pkg/prelude/bootstrap.js:1740
      throw error;
      ^

Error: The module '/opt/key-networks/ztncui/node_modules/argon2/build/Release/argon2.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 93. This version of Node.js requires
NODE_MODULE_VERSION 72. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.dlopen (pkg/prelude/bootstrap.js:2114:28)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1057:18)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at Module.require (pkg/prelude/bootstrap.js:1719:31)
    at require (internal/modules/cjs/helpers.js:74:18)
    at bindings (/snapshot/src/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/snapshot/src/node_modules/argon2/argon2.js:3:37)
    at Module._compile (pkg/prelude/bootstrap.js:1794:22)
````

So I changed the nodejs env variable to match the version of nodejs I saw being installed (v. 16.x) somewhere during the build. The image that resulted after that change in the Dockerfile ran fine.

Maybe you should try a build with the current Dockerfile and see if you get a working ztncui container.

2021-12-04 01:03 UTC, kmahyyg commented
According to your logging, it seems that this problem is not here. There must be something wrong in a deeper layer. I'll try to investigate the reason and respond ASAP. however, since I'm currently on a business trip, some delay are expected. Thanks for your understanding.

2021-12-04 01:06 UTC, kmahyyg commented
And also cc @key-networks  to see if he could give me a hand like some explanation.

2021-12-04 01:30 UTC, kmahyyg commented
@pjv could you please attach full container **build** log for both nodejs version number?

2021-12-04 11:06 UTC, pjv commented
@kmahyyg both build logs are [here](https://gist.github.com/pjv/9a376235f5790dba63e244cb447b3964).

(Line 544 in both of those logs is what made me think to change the environment variable in the Dockerfile).

For me there is no urgency about this issue; I have a working build by changing the environment variable. I just wanted to share that with anyone else who may be trying to use this repo to produce updated builds of ztncui.

Thanks again for your work here.

2021-12-04 13:08 UTC, kmahyyg commented
Excellent. Things just go as what I imagined and your log confirmed this problem.

Here, even if you specified nodejs version 14, it still installed version 16. That's the root cause of this behavior.

https://gist.github.com/pjv/9a376235f5790dba63e244cb447b3964#file-nodejs_major-14-log-L561 

Then all things went normal, however, here:

https://github.com/kmahyyg/ztncui-aio/blob/c8649fc798fe135a4869371acfb687c48bdd46b1/Dockerfile#L21

packed all the binaries stuff or nodejs dependencies using nodejs 14, which made all dependencies inconsistent.

-------

There's two ways to fix this problem, I personally prefer the first one, since it wouldn't break anything in theory.

1. Debugging here:

https://github.com/kmahyyg/ztncui-aio/blob/c8649fc798fe135a4869371acfb687c48bdd46b1/Dockerfile#L13

Why this scirpt does not take corresponding environment variable? This is an unintended behavior. But it is working previously.

2. Change the whole things into nodejs version 16. That's what you have done.


-------

Further comments are welcome.

2021-12-04 16:00 UTC, kmahyyg commented
I found the solution, either you or me fix it should be okay.

The following changes should be done:

- Add detailed explanation about environment variable `NODEJS_MAJOR` in Docker file that this variable is only used in `pkg` tool, not for node.js runtime environment.
- Replace nodejs installation script to: `https://deb.nodesource.com/setup_14.x` , others are the same. Also, local filename might need a change. To prevent further issues, we might need to add a local copy of this script to this git repo. Make sure to check open source license issue and attach corresponding license.
- Rebuild and check using NodeJS 14

2021-12-04 16:01 UTC, kmahyyg requested changes
Check latest comments in discussion of PR.

2021-12-04 16:01 UTC, kmahyyg commented on Dockerfile
> -ENV NODEJS_MAJOR=14
Revert this back. Check comments for more details.

2021-12-04 21:31 UTC, pjv commented
@kmahyyg I reverted the `NODEJS_MAJOR ` environment variable back to 14 and updated the `curl` URL for the nodejs installation on line 13. 

I tested this commit in my environment and it is producing a working image / container.

I did not add the detailed explanation about the environment variable because I do not think I understand well enough where it is and isn't being used, so I will leave that documentation to you whenever you have the chance to add it.

Thank you again for making this code available. It is good to be able to keep ztncui running with an up to date zerotier one node.

2021-12-05 01:34 UTC, kmahyyg approved these changes
Excellent work.

2021-12-05 09:20 UTC, merged

2021-12-05 09:33 UTC, kmahyyg commented
> @kmahyyg I reverted the `NODEJS_MAJOR ` environment variable back to 14 and updated the `curl` URL for the nodejs installation on line 13.
> 
> I tested this commit in my environment and it is producing a working image / container.
> 
> I did not add the detailed explanation about the environment variable because I do not think I understand well enough where it is and isn't being used, so I will leave that documentation to you whenever you have the chance to add it.
> 
> Thank you again for making this code available. It is good to be able to keep ztncui running with an up to date zerotier one node.

It is pretty important for us to keep zerotier up to date. Thanks again for your inquiry. And also, I here personally recommend @key-networks  update the repo they have. Here's a relate ZT official post which respond to a recent vulnerability: https://www.zerotier.com/2021/09/21/incident-response-to-september-20th-2021/ .

2021-12-05 09:47 UTC, kmahyyg commented
By the way, there seems some bad news here: https://github.com/key-networks/ztncui/pull/79

I might need to upgrade to nodejs version 16 later :(